// packages/frontend/components/modals/MembersModal.tsx
import React, { useEffect, useRef, useCallback, useState } from 'react';
import {
  RefreshCw,
  X,
  UserPlus,
  AlertCircle,
  Loader2,
  ArrowUpRight,
} from 'lucide-react';
import { Button } from '../ui/Button';
import { Modal } from '../ui/Modal';
import { TruncateText } from '../ui/TruncateText';
import { projectsApi, usersApi } from '../../services/apiService';
import { projectRolesApi } from '../../services/rolesApi';

interface Member {
  id: string;
  projectId: string;
  userId: string;
  roleId: string;
  user: {
    id: string;
    email: string;
    username: string;
    nickname: string | null;
    avatar: string | null;
    role: string;
    status: string;
  };
  role: {
    id: string;
    name: string;
    description: string | null;
    isSystem: boolean;
  };
  createdAt: string;
}

interface UserSearchResult {
  id: string;
  email: string;
  username: string;
  nickname: string | null;
  avatar: string | null;
  role: string;
  status: string;
}

interface MembersModalProps {
  isOpen: boolean;
  projectId: string;
  onClose: () => void;
}

// 角色名称中文映射
const ROLE_NAME_MAP: Record<string, string> = {
  PROJECT_OWNER: '项目所有者',
  PROJECT_ADMIN: '项目管理员',
  PROJECT_MEMBER: '项目成员',
  PROJECT_EDITOR: '项目编辑者',
  PROJECT_VIEWER: '项目查看者',
};

// 获取角色中文名称
const getRoleDisplayName = (roleName: string): string => {
  return ROLE_NAME_MAP[roleName] || roleName;
};

export const MembersModal: React.FC<MembersModalProps> = ({
  isOpen,
  projectId,
  onClose,
}) => {
  const [members, setMembers] = useState<Member[]>([]);
  const [projectRoles, setProjectRoles] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);
  const [newEmail, setNewEmail] = useState('');
  const [newRoleId, setNewRoleId] = useState('');
  const [adding, setAdding] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [filterRoleId, setFilterRoleId] = useState<string>('');
  const [showTransferModal, setShowTransferModal] = useState(false);
  const [transferring, setTransferring] = useState(false);
  const [transferTarget, setTransferTarget] = useState<Member | null>(null);
  const [searchResults, setSearchResults] = useState<UserSearchResult[]>([]);
  const [searching, setSearching] = useState(false);
  const [selectedUser, setSelectedUser] = useState<UserSearchResult | null>(
    null
  );

  const contentRef = useRef<HTMLDivElement>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const isInitializedRef = useRef(false);

  const loadMembers = useCallback(async () => {
    setErrorMessage('');
    try {
      const response = await projectsApi.getMembers(projectId);
      setMembers((response.data as Member[]) || []);
    } catch (error) {
      setErrorMessage('加载成员列表失败');
    }
  }, [projectId]);

  const loadProjectRoles = useCallback(async () => {
    try {
      const response = await projectRolesApi.list();
      const allRoles = (response.data as any[]) || [];

      // 添加成员时可用的角色（排除 PROJECT_OWNER）
      const addMemberRoles = allRoles.filter((role) => role.name !== 'PROJECT_OWNER');

      setProjectRoles(allRoles);

      // 设置默认角色为 PROJECT_MEMBER
      const defaultRole = addMemberRoles.find(
        (r) => r.name === 'PROJECT_MEMBER'
      );
      if (defaultRole) {
        setNewRoleId((prev) => prev || defaultRole.id);
      }
    } catch (error) {
      console.error('加载项目角色失败:', error);
    }
  }, []);

  // 根据角色筛选成员
  const filteredMembers = filterRoleId
    ? members.filter((member) => member.roleId === filterRoleId)
    : members;

  // 搜索用户
  const searchUsers = useCallback(
    async (query: string) => {
      if (!query.trim()) {
        setSearchResults([]);
        return;
      }

      setSearching(true);
      try {
        const response = await usersApi.search({ search: query, limit: 10 });
        const users = (response.data?.data || []) as UserSearchResult[];

        // 过滤掉已经是成员的用户
        const memberUserIds = members.map((m) => m.userId);
        const availableUsers = users.filter(
          (u) => !memberUserIds.includes(u.id)
        );

        setSearchResults(availableUsers);
      } catch (error) {
        setSearchResults([]);
      } finally {
        setSearching(false);
      }
    },
    [members]
  );

  // 防抖搜索
  useEffect(() => {
    const timer = setTimeout(() => {
      if (showAddForm && !selectedUser) {
        searchUsers(newEmail);
      }
    }, 300);

    return () => clearTimeout(timer);
  }, [newEmail, showAddForm, selectedUser, searchUsers]);

  useEffect(() => {
    if (isOpen && !isInitializedRef.current) {
      isInitializedRef.current = true;

      // 重置状态
      setNewEmail('');
      setNewRoleId('');
      setShowAddForm(false);
      setErrorMessage('');
      setSearchResults([]);
      setSelectedUser(null);

      // 开始加载
      setLoading(true);

      // 并行加载数据
      Promise.all([loadMembers(), loadProjectRoles()]).finally(() => {
        setLoading(false);
      });
    }
    if (!isOpen) {
      isInitializedRef.current = false;
    }
  }, [isOpen, projectId]);

  const handleAddMember = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedUser || !newRoleId) return;

    setAdding(true);
    setErrorMessage('');
    try {
      // 添加成员
      const response = await projectsApi.addMember(projectId, {
        userId: selectedUser.id,
        projectRoleId: newRoleId,
      });

      // 直接添加到列表，避免重新加载
      const newMember = response.data as Member;
      setMembers((prev) => [...prev, newMember]);

      // 重置表单
      setNewEmail('');
      setNewRoleId('');
      setShowAddForm(false);
      setSearchResults([]);
      setSelectedUser(null);
    } catch (error) {
      if (
        (error as Error & { response?: { status?: number } }).response
          ?.status === 403
      ) {
        setErrorMessage('没有权限添加成员');
      } else {
        setErrorMessage('添加成员失败，请重试');
      }
    } finally {
      setAdding(false);
    }
  };

  const handleRemoveMember = async (userId: string) => {
    setErrorMessage('');
    try {
      await projectsApi.removeMember(projectId, userId);
      setMembers((prev) => prev.filter((m) => m.userId !== userId));
    } catch (error) {
      if (
        (error as Error & { response?: { status?: number } }).response
          ?.status === 403
      ) {
        setErrorMessage('没有权限移除成员');
      } else {
        setErrorMessage('移除成员失败，请重试');
      }
    }
  };

  const handleUpdateRole = async (userId: string, roleId: string) => {
    setErrorMessage('');
    try {
      await projectsApi.updateMember(projectId, userId, { roleId });
      setMembers((prev) =>
        prev.map((m) => (m.userId === userId ? { ...m, roleId } : m))
      );
    } catch (error) {
      if (
        (error as Error & { response?: { status?: number } }).response
          ?.status === 403
      ) {
        setErrorMessage('没有权限更新成员角色');
      } else if (
        (error as Error & { response?: { status?: number } }).response
          ?.status === 400
      ) {
        setErrorMessage('不能修改项目所有者的角色');
      } else {
        setErrorMessage('更新角色失败，请重试');
      }
    }
  };

  const handleTransferOwnership = async () => {
    if (!transferTarget) return;

    setTransferring(true);
    setErrorMessage('');
    try {
      await projectsApi.transferOwnership(projectId, transferTarget.userId);

      // 刷新成员列表
      await loadMembers();

      setShowTransferModal(false);
      setTransferTarget(null);
    } catch (error) {
      if (
        (error as Error & { response?: { status?: number } }).response
          ?.status === 403
      ) {
        setErrorMessage('没有权限转让项目');
      } else {
        setErrorMessage('转让项目失败，请重试');
      }
    } finally {
      setTransferring(false);
    }
  };

  return (
    <>
      <Modal
        isOpen={isOpen}
        onClose={onClose}
        title="项目成员"
        footer={
          <Button variant="ghost" onClick={onClose}>
            关闭
          </Button>
        }
      >
        <div className="space-y-4" ref={contentRef}>
          {/* 错误提示 */}
          {errorMessage && (
            <div className="flex items-center gap-2 p-3 bg-red-50 text-red-700 rounded-lg text-sm">
              <AlertCircle size={16} />
              {errorMessage}
            </div>
          )}

          {/* 添加成员按钮/表单 */}
          {!showAddForm ? (
            <button
              onClick={() => setShowAddForm(true)}
              className="w-full py-2 px-4 border-2 border-dashed border-slate-300 rounded-lg
                       text-slate-500 hover:border-indigo-400 hover:text-indigo-600
                       flex items-center justify-center gap-2 transition-colors"
            >
              <UserPlus size={18} />
              添加成员
            </button>
          ) : (
            <form
              onSubmit={handleAddMember}
              className="p-4 bg-slate-50 rounded-lg border border-slate-200 relative"
            >
              <div className="flex items-center gap-2 mb-3">
                <UserPlus size={18} className="text-slate-500" />
                <span className="text-sm font-medium text-slate-700">
                  添加新成员
                </span>
                <button
                  type="button"
                  onClick={() => {
                    setShowAddForm(false);
                    setNewEmail('');
                    setErrorMessage('');
                    setSearchResults([]);
                    setSelectedUser(null);
                  }}
                  className="ml-auto p-1 hover:bg-slate-200 rounded"
                >
                  <X size={16} className="text-slate-500" />
                </button>
              </div>
              <div className="space-y-3">
                {/* 用户搜索输入框 */}
                <div className="relative">
                  <input
                    ref={searchInputRef}
                    type="text"
                    value={newEmail}
                    onChange={(e) => {
                      setNewEmail(e.target.value);
                      setSelectedUser(null);
                    }}
                    placeholder="搜索用户（邮箱或用户名）"
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm"
                    autoComplete="off"
                  />
                  {searching && (
                    <div className="absolute right-3 top-1/2 -translate-y-1/2">
                      <Loader2
                        size={16}
                        className="animate-spin text-slate-400"
                      />
                    </div>
                  )}
                </div>

                {/* 搜索结果下拉列表 */}
                {searchResults.length > 0 && !selectedUser && (
                  <div className="absolute z-10 w-full bg-white border border-slate-300 rounded-lg shadow-lg max-h-60 overflow-y-auto">
                    {searchResults.map((user) => (
                      <button
                        key={user.id}
                        type="button"
                        onClick={() => {
                          setSelectedUser(user);
                          setNewEmail(user.email);
                          setSearchResults([]);
                        }}
                        className="w-full px-3 py-2 hover:bg-slate-100 text-left border-b border-slate-100 last:border-b-0"
                      >
                        <div className="flex items-center gap-2">
                          <div className="w-6 h-6 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 text-xs font-medium flex-shrink-0">
                            {(user.nickname ||
                              user.username ||
                              user.email)[0].toUpperCase()}
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium text-slate-900">
                              <TruncateText>
                                {user.nickname || user.username}
                              </TruncateText>
                            </p>
                            <p className="text-xs text-slate-500">
                              <TruncateText>{user.email}</TruncateText>
                            </p>
                          </div>
                        </div>
                      </button>
                    ))}
                  </div>
                )}

                {/* 已选用户显示 */}
                {selectedUser && (
                  <div className="flex items-center gap-2 p-2 bg-indigo-50 border border-indigo-200 rounded-lg">
                    <div className="w-6 h-6 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 text-xs font-medium flex-shrink-0">
                      {(selectedUser.nickname ||
                        selectedUser.username ||
                        selectedUser.email)[0].toUpperCase()}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-slate-900">
                        <TruncateText>
                          {selectedUser.nickname || selectedUser.username}
                        </TruncateText>
                      </p>
                      <p className="text-xs text-slate-500">
                        <TruncateText>{selectedUser.email}</TruncateText>
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => {
                        setSelectedUser(null);
                        setNewEmail('');
                      }}
                      className="p-1 hover:bg-indigo-200 rounded flex-shrink-0"
                    >
                      <X size={14} className="text-slate-500" />
                    </button>
                  </div>
                )}

                {/* 角色选择和添加按钮 */}
                <div className="flex gap-2">
                  <select
                    value={newRoleId}
                    onChange={(e) => setNewRoleId(e.target.value)}
                    className="flex-1 px-3 py-2 border border-slate-300 rounded-lg text-sm"
                    disabled={loading}
                  >
                    <option value="">请选择角色</option>
                    {projectRoles
                      .filter((role) => role.name !== 'PROJECT_OWNER')
                      .map((role) => (
                        <option key={role.id} value={role.id}>
                          {getRoleDisplayName(role.name)}
                        </option>
                      ))}
                  </select>
                  <Button
                    type="submit"
                    size="sm"
                    disabled={adding || !selectedUser || !newRoleId}
                  >
                    {adding ? '添加中...' : '添加'}
                  </Button>
                </div>
              </div>
            </form>
          )}

          {/* 筛选条 */}
          {members.length > 0 && (
            <div className="flex items-center justify-between">
              <span className="text-sm text-slate-500">
                共 {filteredMembers.length} 人
              </span>
              <select
                value={filterRoleId}
                onChange={(e) => setFilterRoleId(e.target.value)}
                className="px-3 py-1.5 border border-slate-300 rounded bg-white text-sm text-slate-700"
              >
                <option value="">所有角色</option>
                {projectRoles.map((role) => (
                  <option key={role.id} value={role.id}>
                    {getRoleDisplayName(role.name)}
                  </option>
                ))}
              </select>
            </div>
          )}

          {/* 成员列表 */}
          <div className="space-y-2">
            {loading ? (
              <div className="flex items-center justify-center py-8">
                <RefreshCw size={20} className="animate-spin text-slate-400" />
                <span className="ml-2 text-slate-500">加载中...</span>
              </div>
            ) : filteredMembers.length === 0 ? (
              <div className="text-center py-8 text-slate-500">
                {filterRoleId ? '没有符合条件的成员' : '暂无成员'}
              </div>
            ) : (
              filteredMembers.map((member) => {
                const isOwner = member.role.name === 'PROJECT_OWNER';
                const displayName =
                  member.user.nickname ||
                  member.user.username ||
                  member.user.email ||
                  '未知用户';
                const avatarLetter = displayName[0]?.toUpperCase() || '?';

                return (
                  <div
                    key={member.id}
                    className="flex items-center gap-3 p-3 bg-slate-50 rounded-lg"
                  >
                    <div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 text-sm font-medium flex-shrink-0">
                      {avatarLetter}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-slate-900">
                        <TruncateText>{displayName}</TruncateText>
                      </p>
                      <p className="text-xs text-slate-500">
                        <TruncateText>
                          {member.user.email || '无邮箱'}
                        </TruncateText>
                      </p>
                    </div>
                    <select
                      value={member.roleId}
                      onChange={(e) =>
                        handleUpdateRole(member.userId, e.target.value)
                      }
                      disabled={isOwner}
                      className={`px-2 py-1 text-xs border border-slate-300 rounded bg-white flex-shrink-0 ${
                        isOwner ? 'opacity-50 cursor-not-allowed' : ''
                      }`}
                    >
                      {projectRoles
                        .filter((role) => role.name !== 'PROJECT_OWNER')
                        .map((role) => (
                          <option key={role.id} value={role.id}>
                            {getRoleDisplayName(role.name)}
                          </option>
                        ))}
                    </select>
                    {!isOwner && (
                      <button
                        onClick={() => {
                          setTransferTarget(member);
                          setShowTransferModal(true);
                        }}
                        className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded flex-shrink-0"
                        title="转让项目所有权"
                      >
                        <ArrowUpRight size={16} />
                      </button>
                    )}
                    {!isOwner && (
                      <button
                        onClick={() => handleRemoveMember(member.userId)}
                        className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded flex-shrink-0"
                        title="移除成员"
                      >
                        <X size={16} />
                      </button>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      </Modal>

      {/* 转让确认弹窗 */}
      {showTransferModal && transferTarget && (
        <Modal
          isOpen={showTransferModal}
          onClose={() => {
            setShowTransferModal(false);
            setTransferTarget(null);
          }}
          title="转让项目所有权"
          footer={
            <>
              <Button
                variant="ghost"
                onClick={() => {
                  setShowTransferModal(false);
                  setTransferTarget(null);
                }}
              >
                取消
              </Button>
              <Button
                onClick={handleTransferOwnership}
                disabled={transferring}
                className="bg-indigo-600 hover:bg-indigo-700"
              >
                {transferring ? '转让中...' : '确认转让'}
              </Button>
            </>
          }
        >
          <div className="space-y-4">
            <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-lg">
              <AlertCircle
                size={20}
                className="text-amber-600 flex-shrink-0 mt-0.5"
              />
              <div className="text-sm text-amber-900">
                <p className="font-semibold mb-1">重要提示</p>
                <p className="text-amber-800">
                  转让项目所有权后，您将失去项目所有者权限，并自动降级为项目管理员。此操作不可撤销。
                </p>
              </div>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-medium text-slate-700">转让给：</p>
              <div className="flex items-center gap-3 p-3 bg-slate-50 rounded-lg">
                <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 text-sm font-medium flex-shrink-0">
                  {(transferTarget.user.nickname ||
                    transferTarget.user.username ||
                    transferTarget.user.email)[0].toUpperCase()}
                </div>
                <div>
                  <p className="text-sm font-medium text-slate-900">
                    {transferTarget.user.nickname ||
                      transferTarget.user.username}
                  </p>
                  <p className="text-xs text-slate-500">
                    {transferTarget.user.email}
                  </p>
                </div>
              </div>
            </div>

            <div className="text-xs text-slate-500">
              <p>• 新所有者将获得项目的完全控制权</p>
              <p>• 您将成为该项目的管理员</p>
              <p>• 确认转让后，新所有者可以管理项目成员和权限</p>
            </div>
          </div>
        </Modal>
      )}
    </>
  );
};

export default MembersModal;

// apps/frontend-vue/src/components/MembersModal.vue
<template>
  <v-dialog :model-value="isOpen" @update:model-value="$emit('update:isOpen', $event)" max-width="600" persistent>
    <v-card>
      <v-card-title class="d-flex align-center justify-space-between">
        <span>{{ t('project.members') }}</span>
        <v-btn icon="mdi-close" variant="text" size="small" @click="onClose" />
      </v-card-title>

      <v-card-text class="pa-4">
        <v-alert v-if="errorMessage" type="error" variant="tonal" class="mb-4">
          {{ errorMessage }}
        </v-alert>

        <v-btn
          v-if="canManageMembers && !showAddForm"
          block
          variant="outlined"
          color="primary"
          class="mb-4"
          @click="showAddForm = true"
        >
          <v-icon start>mdi-account-plus</v-icon>
          {{ t('project.addMember') }}
        </v-btn>

        <v-form v-if="showAddForm" class="mb-4 pa-4 rounded bg-surface-variant" @submit.prevent="handleAddMember">
          <div class="d-flex align-center mb-3">
            <v-icon start size="18">mdi-account-plus</v-icon>
            <span class="text-body-2 font-weight-medium">{{ t('project.addNewMember') }}</span>
            <v-spacer />
            <v-btn icon="mdi-close" variant="text" size="x-small" @click="resetAddForm" />
          </div>

          <v-autocomplete
            v-model="selectedUser"
            v-model:search="newEmail"
            :items="searchResults"
            :loading="searching"
            item-title="email"
            item-value="id"
            :label="t('project.searchUser')"
            :return-object="true"
            class="mb-3"
            auto-select-first
            no-filter
            @update:search="debouncedSearch"
          >
            <template #item="{ props: itemProps, item }">
              <v-list-item v-bind="itemProps" :title="item.raw.nickname || item.raw.username" :subtitle="item.raw.email">
                <template #prepend>
                  <v-avatar size="24" color="primary" class="mr-2">
                    <span class="text-caption">{{ (item.raw.nickname || item.raw.username || '?')[0]?.toUpperCase() }}</span>
                  </v-avatar>
                </template>
              </v-list-item>
            </template>
          </v-autocomplete>

          <v-select
            v-model="newRoleId"
            :items="availableRoles"
            item-title="name"
            item-value="id"
            :label="t('project.selectRole')"
            class="mb-3"
          >
            <template #item="{ props: itemProps, item }">
              <v-list-item v-bind="itemProps" :title="getRoleDisplayName(item.raw.name)" />
            </template>
            <template #selection="{ item }">
              {{ getRoleDisplayName(item.raw.name) }}
            </template>
          </v-select>

          <v-btn type="submit" color="primary" block :loading="adding" :disabled="!selectedUser || !newRoleId">
            {{ t('common.add') }}
          </v-btn>
        </v-form>

        <div v-if="filteredMembers.length > 0" class="d-flex justify-space-between align-center mb-3">
          <span class="text-body-2 text-medium-emphasis">{{ t('project.memberCount', { count: filteredMembers.length }) }}</span>
          <v-select
            v-model="filterRoleId"
            :items="projectRoles"
            item-title="name"
            item-value="id"
            :label="t('project.filterRole')"
            density="compact"
            variant="outlined"
            hide-details
            style="max-width: 150px"
          >
            <template #item="{ props: itemProps, item }">
              <v-list-item v-bind="itemProps" :title="getRoleDisplayName(item.raw.name)" />
            </template>
            <template #selection="{ item }">
              {{ getRoleDisplayName(item.raw.name) }}
            </template>
          </v-select>
        </div>

        <v-list v-if="loading">
          <v-list-item>
            <template #prepend>
              <v-progress-circular indeterminate size="24" />
            </template>
            <v-list-item-title>{{ t('common.loading') }}</v-list-item-title>
          </v-list-item>
        </v-list>

        <v-list v-else-if="filteredMembers.length === 0">
          <v-list-item>
            <v-list-item-title class="text-center text-medium-emphasis">
              {{ filterRoleId ? t('project.noMatchingMembers') : t('project.noMembers') }}
            </v-list-item-title>
          </v-list-item>
        </v-list>

        <v-list v-else density="compact">
          <v-list-item v-for="member in filteredMembers" :key="member.id" class="mb-2 rounded bg-surface-variant">
            <template #prepend>
              <v-avatar size="32" color="primary" class="mr-3">
                <span>{{ (member.nickname || member.username || member.email || '?')[0]?.toUpperCase() }}</span>
              </v-avatar>
            </template>

            <v-list-item-title>{{ member.nickname || member.username }}</v-list-item-title>
            <v-list-item-subtitle>{{ member.email }}</v-list-item-subtitle>

            <v-list-item-action v-if="member.projectRoleName === 'PROJECT_OWNER'">
              <v-chip size="small" color="primary" variant="tonal">{{ t('project.roleOwner') }}</v-chip>
            </v-list-item-action>

            <v-list-item-action v-else-if="canAssignRoles">
              <div class="d-flex align-center ga-2">
                <v-select
                  :model-value="member.projectRoleId"
                  :items="availableRoles"
                  item-title="name"
                  item-value="id"
                  density="compact"
                  variant="outlined"
                  hide-details
                  style="max-width: 120px"
                  @update:model-value="handleUpdateRole(member.id, $event)"
                >
                  <template #item="{ props: itemProps, item }">
                    <v-list-item v-bind="itemProps" :title="getRoleDisplayName(item.raw.name)" />
                  </template>
                  <template #selection="{ item }">
                    {{ getRoleDisplayName(item.raw.name) }}
                  </template>
                </v-select>
                <v-btn
                  icon="mdi-close"
                  variant="text"
                  size="small"
                  color="error"
                  @click="handleRemoveMember(member.id)"
                />
              </div>
            </v-list-item-action>
          </v-list-item>
        </v-list>
      </v-card-text>

      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="onClose">{{ t('common.close') }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <v-dialog v-model="showTransferModal" max-width="400" persistent>
    <v-card>
      <v-card-title>{{ t('project.transferOwnership') }}</v-card-title>
      <v-card-text>
        <v-alert type="warning" variant="tonal" class="mb-4">
          <strong>{{ t('project.importantNotice') }}</strong>
          <p class="mt-2">{{ t('project.transferWarning') }}</p>
        </v-alert>

        <div class="d-flex align-center pa-3 rounded bg-surface-variant">
          <v-avatar size="40" color="primary" class="mr-3">
            <span>{{ (transferTarget?.nickname || transferTarget?.username || transferTarget?.email || '?')[0]?.toUpperCase() }}</span>
          </v-avatar>
          <div>
            <div class="font-weight-medium">{{ transferTarget?.nickname || transferTarget?.username }}</div>
            <div class="text-caption text-medium-emphasis">{{ transferTarget?.email }}</div>
          </div>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="showTransferModal = false; transferTarget = null">{{ t('common.cancel') }}</v-btn>
        <v-btn color="primary" :loading="transferring" @click="handleTransferOwnership">{{ t('project.confirmTransfer') }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { projectsApi } from '@/services/projectsApi';
import { projectRolesApi } from '@/services/rolesApi';
import { usersApi } from '@/services/usersApi';
import { useI18n } from '@/composables/useI18n';

const { t } = useI18n();

interface Props {
  isOpen: boolean;
  projectId: string;
  onClose: () => void;
}

const props = defineProps<Props>();

const ROLE_NAME_MAP: Record<string, string> = {
  PROJECT_OWNER: '项目所有者',
  PROJECT_ADMIN: '项目管理员',
  PROJECT_MEMBER: '项目成员',
  PROJECT_EDITOR: '项目编辑者',
  PROJECT_VIEWER: '项目查看者',
};

const getRoleDisplayName = (roleName: string): string => {
  const key = `project.role${roleName.replace('PROJECT_', '_').slice(1)}`;
  const translated = t(key);
  return translated !== key ? translated : ROLE_NAME_MAP[roleName] || roleName;
};

const members = ref<any[]>([]);
const projectRoles = ref<any[]>([]);
const loading = ref(false);
const showAddForm = ref(false);
const newEmail = ref('');
const newRoleId = ref('');
const adding = ref(false);
const errorMessage = ref('');
const filterRoleId = ref('');
const canManageMembers = ref(false);
const canAssignRoles = ref(false);

const selectedUser = ref<any | null>(null);
const searchResults = ref<any[]>([]);
const searching = ref(false);

const showTransferModal = ref(false);
const transferTarget = ref<any | null>(null);
const transferring = ref(false);

const filteredMembers = computed(() => {
  if (!filterRoleId.value) return members.value;
  return members.value.filter(m => m.projectRoleId === filterRoleId.value);
});

const availableRoles = computed(() => {
  return projectRoles.value.filter(r => r.name !== 'PROJECT_OWNER');
});

let searchTimeout: ReturnType<typeof setTimeout> | null = null;

function debouncedSearch(query: string) {
  if (searchTimeout) clearTimeout(searchTimeout);
  if (!query.trim()) {
    searchResults.value = [];
    return;
  }
  searching.value = true;
  searchTimeout = setTimeout(async () => {
    try {
      const response = await usersApi.search({ keyword: query, limit: 10 });
      const users = response.data?.users || [];
      const memberUserIds = members.value.map((m: any) => m.id);
      searchResults.value = (users as any[]).filter((u: any) => !memberUserIds.includes(u.id));
    } catch {
      searchResults.value = [];
    } finally {
      searching.value = false;
    }
  }, 300);
}

async function loadMembers() {
  errorMessage.value = '';
  try {
    const response = await projectsApi.getMembers(props.projectId);
    members.value = ((response.data || []) as any[]).map((m: any) => ({ ...m, userId: m.id }));
  } catch {
    errorMessage.value = t('project.loadMembersError');
  }
}

async function loadProjectRoles() {
  try {
    const response = await projectRolesApi.getByProject(props.projectId);
    projectRoles.value = (response.data as any[]) || [];
    const defaultRole = availableRoles.value.find((r: any) => r.name === 'PROJECT_MEMBER');
    if (defaultRole) {
      newRoleId.value = defaultRole.id;
    }
  } catch (error) {
    console.error(t('project.loadRolesError'), error);
  }
}

async function handleAddMember() {
  if (!selectedUser.value || !newRoleId.value) return;

  adding.value = true;
  errorMessage.value = '';
  try {
    const response = await projectsApi.addMember(props.projectId, {
      userId: selectedUser.value.id,
      projectRoleId: newRoleId.value,
    });

    const memberData = response.data as any;
    members.value.push({
      id: memberData.user.id,
      userId: memberData.user.id,
      email: memberData.user.email,
      username: memberData.user.username,
      nickname: memberData.user.nickname,
      avatar: memberData.user.avatar,
      projectRoleId: memberData.projectRoleId,
      projectRoleName: memberData.projectRole.name,
      joinedAt: memberData.createdAt,
    });

    resetAddForm();
  } catch (error: any) {
    if (error?.response?.status === 403) {
      errorMessage.value = t('project.addMemberNoPermission');
    } else {
      errorMessage.value = t('project.addMemberError');
    }
  } finally {
    adding.value = false;
  }
}

function resetAddForm() {
  showAddForm.value = false;
  newEmail.value = '';
  newRoleId.value = '';
  selectedUser.value = null;
  searchResults.value = [];
}

async function handleRemoveMember(userId: string) {
  errorMessage.value = '';
  try {
    await projectsApi.removeMember(props.projectId, userId);
    members.value = members.value.filter((m: any) => m.userId !== userId);
  } catch (error: any) {
    if (error?.response?.status === 403) {
      errorMessage.value = t('project.removeMemberNoPermission');
    } else {
      errorMessage.value = t('project.removeMemberError');
    }
  }
}

async function handleUpdateRole(userId: string, projectRoleId: string) {
  errorMessage.value = '';
  try {
    await projectsApi.updateMember(props.projectId, userId, { projectRoleId });
    const member = members.value.find((m: any) => m.userId === userId);
    if (member) {
      member.projectRoleId = projectRoleId;
    }
  } catch (error: any) {
    if (error?.response?.status === 403) {
      errorMessage.value = t('project.updateRoleNoPermission');
    } else if (error?.response?.status === 400) {
      errorMessage.value = t('project.cannotModifyOwnerRole');
    } else {
      errorMessage.value = t('project.updateRoleError');
    }
  }
}

async function handleTransferOwnership() {
  if (!transferTarget.value) return;

  transferring.value = true;
  errorMessage.value = '';
  try {
    await projectsApi.transferOwnership(props.projectId, transferTarget.value.userId);
    await loadMembers();
    showTransferModal.value = false;
    transferTarget.value = null;
  } catch (error: any) {
    if (error?.response?.status === 403) {
      errorMessage.value = t('project.transferNoPermission');
    } else {
      errorMessage.value = t('project.transferError');
    }
  } finally {
    transferring.value = false;
  }
}

watch(() => props.isOpen, async (isOpen) => {
  if (isOpen) {
    loading.value = true;
    await Promise.all([loadMembers(), loadProjectRoles()]);
    loading.value = false;
  }
});
</script>
